# Copyright 2020 Adam Chalkley
#
# https://github.com/atc0005/go-ci
#
# Licensed under the MIT License. See LICENSE file in the project root for
# full license information.

name: Linting

# Run builds for Pull Requests (new, updated)
# `synchronized` seems to equate to pushing new commits to a linked branch
# (whether force-pushed or not)
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  linting:
    name: Lint Dockerfile files
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container:
      image: index.docker.io/hadolint/hadolint:v2.8.0-debian

    steps:
      - name: Check out code
        uses: actions/checkout@v2.4.0

      - name: Run hadolint against all Dockerfile files
        run: |
          hadolint stable/linting/Dockerfile
          hadolint stable/combined/Dockerfile
          hadolint stable/build/alpine-x64/Dockerfile
          hadolint stable/build/alpine-x86/Dockerfile
          hadolint stable/build/debian/Dockerfile
          hadolint oldstable/Dockerfile
          hadolint unstable/Dockerfile
