# Copyright 2022 Adam Chalkley
#
# https://github.com/atc0005/go-ci
#
# Licensed under the MIT License. See LICENSE file in the project root for
# full license information.

name: Project Analysis

on:
  pull_request:
    # `synchronized` seems to equate to pushing new commits to a linked branch
    # (whether force-pushed or not)
    types: [opened, synchronize]

  # Allow workflow to be triggered manually.
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    uses: atc0005/shared-project-resources/.github/workflows/lint-project-files.yml@master
